# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
qq = QuizQuestion.create(text: "Ko nije clan QA tima?")
qq.quiz_question_answers.create(text: "Mita", correct: false)
qq.quiz_question_answers.create(text: "Mario", correct: true)
qq.quiz_question_answers.create(text: "Petar", correct: false)
qq.quiz_question_answers.create(text: "Boza", correct: false)
qq = QuizQuestion.create(text: "Koje su boje strumfovi?")
qq.quiz_question_answers.create(text: "Zute", correct: false)
qq.quiz_question_answers.create(text: "Plave", correct: true)
qq.quiz_question_answers.create(text: "Zelene", correct: false)
qq.quiz_question_answers.create(text: "Crvene", correct: false)
qq = QuizQuestion.create(text: "Ciji se nos u lazi povecava?")
qq.quiz_question_answers.create(text: "Kermitu", correct: false)
qq.quiz_question_answers.create(text: "Mikiju", correct: false)
qq.quiz_question_answers.create(text: "Pinokiju", correct: true)
qq.quiz_question_answers.create(text: "Silji", correct: false)
qq = QuizQuestion.create(text: "Ahilovo jedino ranjivo mesto?")
qq.quiz_question_answers.create(text: "Peta", correct: true)
qq.quiz_question_answers.create(text: "Koleno", correct: false)
qq.quiz_question_answers.create(text: "Oko", correct: false)
qq.quiz_question_answers.create(text: "Srce", correct: false)
qq = QuizQuestion.create(text: "Delphi je?")
qq.quiz_question_answers.create(text: "Prorociste u Italiji", correct: false)
qq.quiz_question_answers.create(text: "Morski sisar", correct: false)
qq.quiz_question_answers.create(text: "Grcko slovo", correct: false)
qq.quiz_question_answers.create(text: "Programski jezik", correct: true)
qq = QuizQuestion.create(text: "Predsednik SAD je?")
qq.quiz_question_answers.create(text: "Vladimir Putin", correct: false)
qq.quiz_question_answers.create(text: "Barak Obama", correct: true)
qq.quiz_question_answers.create(text: "Boris Tadic", correct: false)
qq.quiz_question_answers.create(text: "Ronald Regan", correct: false)
qq = QuizQuestion.create(text: "Cetvrto slovo abecede?")
qq.quiz_question_answers.create(text: "D", correct: true)
qq.quiz_question_answers.create(text: "F", correct: false)
qq.quiz_question_answers.create(text: "P", correct: false)
qq.quiz_question_answers.create(text: "S", correct: false)
qq = QuizQuestion.create(text: "U kojoj zemlji su rodjene olimpijske igre?")
qq.quiz_question_answers.create(text: "Mezopotamiji", correct: false)
qq.quiz_question_answers.create(text: "Grckoj", correct: true)
qq.quiz_question_answers.create(text: "Kini", correct: false)
qq.quiz_question_answers.create(text: "Egiptu", correct: false)
qq = QuizQuestion.create(text: "Odakle je Kristofor Kolumbo?")
qq.quiz_question_answers.create(text: "Spanija", correct: false)
qq.quiz_question_answers.create(text: "Djenova", correct: true)
qq.quiz_question_answers.create(text: "Portugal", correct: false)
qq.quiz_question_answers.create(text: "Venecija", correct: false)
qq = QuizQuestion.create(text: "Otava je glavni grad?")
qq.quiz_question_answers.create(text: "Teksasa", correct: false)
qq.quiz_question_answers.create(text: "Engleske", correct: false)
qq.quiz_question_answers.create(text: "Kanade", correct: true)
qq.quiz_question_answers.create(text: "Bolivije", correct: false)
